# 1 "data/maps/PetalburgCity_House2/scripts.pory"

# 2 "data/maps/PetalburgCity_House2/scripts.pory"
PetalburgCity_House2_MapScripts::
# 3 "data/maps/PetalburgCity_House2/scripts.pory"
	.byte 0
# 4 "data/maps/PetalburgCity_House2/scripts.pory"

# 5 "data/maps/PetalburgCity_House2/scripts.pory"
PetalburgCity_House2_EventScript_Woman::
# 6 "data/maps/PetalburgCity_House2/scripts.pory"
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
# 7 "data/maps/PetalburgCity_House2/scripts.pory"
	end
# 8 "data/maps/PetalburgCity_House2/scripts.pory"

# 9 "data/maps/PetalburgCity_House2/scripts.pory"
PetalburgCity_House2_EventScript_SchoolKid::
# 10 "data/maps/PetalburgCity_House2/scripts.pory"
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
# 11 "data/maps/PetalburgCity_House2/scripts.pory"
	end
# 12 "data/maps/PetalburgCity_House2/scripts.pory"

# 13 "data/maps/PetalburgCity_House2/scripts.pory"
PetalburgCity_House2_Text_NormanBecameGymLeader:
# 14 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "Everyone has loved Norman since he\n"
# 15 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "became our town's Gym Leader.\p"
# 16 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "It's sad to see him go.$"
# 17 "data/maps/PetalburgCity_House2/scripts.pory"

# 18 "data/maps/PetalburgCity_House2/scripts.pory"
PetalburgCity_House2_Text_BattledNormanOnce:
# 19 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "I battled NORMAN once, but, whew,\n"
# 20 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "he was way too strong.\p"
# 21 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "How would I put it?\p"
# 22 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "I just got the feeling that he\n"
# 23 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "lives for Pokémon.$"
